cabal-version:         2.4

name:                  helma
version:               0.9.0.0
synopsis:              HELMA - Haskellish Esoteric Limited Minimal Automaton
description:           Please see the README on GitHub at <https://github.com/helvm/helma#readme>
homepage:              http://helvm.org/helma/
bug-reports:           https://github.com/helvm/helma/issues

license:               Apache-2.0
license-file:          docs/license/LICENSE-APACHE
author:                Kamil Adam
maintainer:            kamil.adam.zabinski@gmail.com
copyright:             2020-2026 WriteOnly Developers

category:              Language
build-type:            Simple
extra-source-files:
  docs/developers/CHANGELOG.md
  docs/README.md

tested-with:           GHC == 9.12.4

source-repository head
  type:                git
  location:            https://github.com/helvm/helma

flag ghcoptions
  description:         compile with options
  manual:              True
  default:             False

common common-options
  build-depends:
      base                 <  4.22
    , relude               <  1.3
    , rio
    , bytestring
    , dlist
    , JuicyPixels
    , mono-traversable
    , mtl
    , text
  mixins:
      base hiding (Prelude)
    , relude (Relude as Prelude, Relude.Extra, Data.Text)
  default-language:    Haskell2010
  default-extensions:
    EmptyDataDecls
    ExistentialQuantification
    FlexibleContexts
    FlexibleInstances
    FunctionalDependencies
    GADTs
    GeneralizedNewtypeDeriving
    InstanceSigs
    KindSignatures
    LambdaCase
    MultiParamTypeClasses
    MultiWayIf
    NamedFieldPuns
--    NoImplicitPrelude
    OverloadedStrings
    PartialTypeSignatures
    PatternGuards
    PolyKinds
    RankNTypes
    RecordWildCards
    ScopedTypeVariables
    StandaloneDeriving
    TupleSections
    TypeFamilies
    TypeSynonymInstances
    ViewPatterns
--    CPP
  --  TemplateHaskell
--    ForeignFunctionInterface
--    MagicHash
--    UnliftedFFITypes
    TypeOperators
--    UnboxedTuples
--    PackageImports
--    QuasiQuotes
--    DeriveAnyClass
--    DeriveLift
--    StaticPointers
    DerivingStrategies
    ConstraintKinds
    StrictData
    UnicodeSyntax
  if flag(ghcoptions)
    ghc-options:
      -Wall
      -Wcompat
      -Widentities
      -Wincomplete-uni-patterns
      -Wincomplete-record-updates
      -Wredundant-constraints
      -Wnoncanonical-monad-instances
      -fhide-source-paths
--      -Wmissing-export-lists FIXME
       -Wpartial-fields
      -Wmissing-deriving-strategies
      -fwrite-ide-info
      -hiedir=.hie
--      -Wunused-packages
      -fprint-potential-instances
      -Werror
      -O2
      -fexpose-all-unfoldings
      -fspecialise-aggressively

library
  import:              common-options
  hs-source-dirs:      hs/src
  exposed-modules:

    HelVM.HelMA.Evaluator

    HelVM.HelMA.Automaton.API.AppOptions
    HelVM.HelMA.Automaton.API.AutomatonOptions
    HelVM.HelMA.Automaton.API.BoolTypes
    HelVM.HelMA.Automaton.API.MemoryOptions
    HelVM.HelMA.Automaton.API.AutoOptions
    HelVM.HelMA.Automaton.API.Emit
    HelVM.HelMA.Automaton.API.Env
    HelVM.HelMA.Automaton.API.EvalParams
    HelVM.HelMA.Automaton.API.LogLevel
    HelVM.HelMA.Automaton.API.IOTypes
    HelVM.HelMA.Automaton.API.Lang
    HelVM.HelMA.Automaton.API.OptimizationLevel
    
    HelVM.HelMA.Automaton.Automaton

    HelVM.HelMA.Automaton.Eff.AutomatonEff
    HelVM.HelMA.Automaton.Eff.FreeEff
    HelVM.HelMA.Automaton.Eff.GADTEff
    HelVM.HelMA.Automaton.Eff.Mock
    HelVM.HelMA.Automaton.Eff.MockEff
    HelVM.HelMA.Automaton.Eff.MockLogger
    HelVM.HelMA.Automaton.Eff.MonadEff

    HelVM.HelMA.Automaton.Extra 

    HelVM.HelMA.Automaton.Instruction
    HelVM.HelMA.Automaton.Instruction.Groups.CFInstruction
    HelVM.HelMA.Automaton.Instruction.Groups.IOInstruction
    HelVM.HelMA.Automaton.Instruction.Groups.LSInstruction
    HelVM.HelMA.Automaton.Instruction.Groups.SMInstruction

    HelVM.HelMA.Automaton.Instruction.Extras.Constructors
    HelVM.HelMA.Automaton.Instruction.Extras.Patterns
    HelVM.HelMA.Automaton.Instruction.Extras.Common
    HelVM.HelMA.Automaton.Instruction.Extras.TextExtra

    HelVM.HelMA.Automaton.Optimizer
    HelVM.HelMA.Automaton.Optimizer.ConstantFoldingOptimizer
    HelVM.HelMA.Automaton.Optimizer.DeadCodeOptimizer
    HelVM.HelMA.Automaton.Optimizer.MarkRemovingOptimizer
    HelVM.HelMA.Automaton.Optimizer.PeepholeOptimizer

    HelVM.HelMA.Automaton.ReadPExtra

    HelVM.HelMA.Automaton.Symbol

    HelVM.HelMA.Automaton.Trampoline

    HelVM.HelMA.Automaton.Types.CellType
    HelVM.HelMA.Automaton.Types.DumpType
    HelVM.HelMA.Automaton.Types.IntCellType
    HelVM.HelMA.Automaton.Types.LabelType
    HelVM.HelMA.Automaton.Types.RAMType
    HelVM.HelMA.Automaton.Types.StackType

    HelVM.HelMA.Automaton.Combiner
    HelVM.HelMA.Automaton.Combiner.ALU
    HelVM.HelMA.Automaton.Combiner.CPU
    HelVM.HelMA.Automaton.Combiner.LSU
    HelVM.HelMA.Automaton.Combiner.RAM

    HelVM.HelMA.Automaton.WrapTokenList

    HelVM.HelMA.Automata.BrainFuck.Evaluator

    HelVM.HelMA.Automata.BrainFuck.API.ImplType

    HelVM.HelMA.Automata.BrainFuck.Common.SimpleInstruction
    HelVM.HelMA.Automata.BrainFuck.Common.Symbol
    HelVM.HelMA.Automata.BrainFuck.Common.TapeOfSymbols

    HelVM.HelMA.Automata.BrainFuck.Impl.Fast.Evaluator
    HelVM.HelMA.Automata.BrainFuck.Impl.Fast.Instruction
    HelVM.HelMA.Automata.BrainFuck.Impl.Fast.Optimizer
    HelVM.HelMA.Automata.BrainFuck.Impl.Fast.Parser

    HelVM.HelMA.Automata.BrainFuck.Impl.Flat.Evaluator
    HelVM.HelMA.Automata.BrainFuck.Impl.Flat.Instruction
    HelVM.HelMA.Automata.BrainFuck.Impl.Flat.Parser
    HelVM.HelMA.Automata.BrainFuck.Impl.Flat.TableOfInstructions

    HelVM.HelMA.Automata.BrainFuck.Impl.Tree.Evaluator
    HelVM.HelMA.Automata.BrainFuck.Impl.Tree.Instruction
    HelVM.HelMA.Automata.BrainFuck.Impl.Tree.InstructionUnit
    HelVM.HelMA.Automata.BrainFuck.Impl.Tree.Parser

    HelVM.HelMA.Automata.Cat.Evaluator

    HelVM.HelMA.Automata.ETA.API.AutomatonType

    HelVM.HelMA.Automata.ETA.Addressing
    HelVM.HelMA.Automata.ETA.Automaton
    HelVM.HelMA.Automata.ETA.Evaluator
    HelVM.HelMA.Automata.ETA.Lexer
    HelVM.HelMA.Automata.ETA.OperandParsers
    HelVM.HelMA.Automata.ETA.Optimizer
    HelVM.HelMA.Automata.ETA.Parser
    HelVM.HelMA.Automata.ETA.SimpleParams
    HelVM.HelMA.Automata.ETA.Symbol
    HelVM.HelMA.Automata.ETA.Token

    HelVM.HelMA.Automata.FALSE.Evaluator
    HelVM.HelMA.Automata.FALSE.Expression
    HelVM.HelMA.Automata.FALSE.Parser

    HelVM.HelMA.Automata.LazyK.Automaton
    HelVM.HelMA.Automata.LazyK.Constants
    HelVM.HelMA.Automata.LazyK.Evaluator
    HelVM.HelMA.Automata.LazyK.InputEncoder
    HelVM.HelMA.Automata.LazyK.Lambda
    HelVM.HelMA.Automata.LazyK.Lexer
    HelVM.HelMA.Automata.LazyK.Parser
    HelVM.HelMA.Automata.LazyK.Reducer
    
    HelVM.HelMA.Automata.Piet.CodelSize
    HelVM.HelMA.Automata.Piet.Combiner
    HelVM.HelMA.Automata.Piet.Compiler
    HelVM.HelMA.Automata.Piet.Evaluator
    HelVM.HelMA.Automata.Piet.Filler
    HelVM.HelMA.Automata.Piet.MatrixBuilder
    HelVM.HelMA.Automata.Piet.Parser
    HelVM.HelMA.Automata.Piet.ToRGB8

    HelVM.HelMA.Automata.Piet.API.ImplType
    HelVM.HelMA.Automata.Piet.API.LexerType

    HelVM.HelMA.Automata.Piet.Automaton.Collision
    HelVM.HelMA.Automata.Piet.Automaton.StepState

    HelVM.HelMA.Automata.Piet.Combiner.ALU
    HelVM.HelMA.Automata.Piet.Combiner.CPU

    HelVM.HelMA.Automata.Piet.LLVM.Evaluator
    HelVM.HelMA.Automata.Piet.LLVM.ImageReader
    HelVM.HelMA.Automata.Piet.LLVM.Parser
    HelVM.HelMA.Automata.Piet.Types.SyntaxGraph
    HelVM.HelMA.Automata.Piet.LLVM.SyntaxVisualizer
    HelVM.HelMA.Automata.Piet.LLVM.WhiteCodelSlider

    HelVM.HelMA.Automata.Piet.Types.ChromaticColor
    HelVM.HelMA.Automata.Piet.Types.CodelChooser
    HelVM.HelMA.Automata.Piet.Types.Color
    HelVM.HelMA.Automata.Piet.Types.Command
    HelVM.HelMA.Automata.Piet.Types.Coordinates
    HelVM.HelMA.Automata.Piet.Types.Course
    HelVM.HelMA.Automata.Piet.Types.Cursor
    HelVM.HelMA.Automata.Piet.Types.Cyclic
    HelVM.HelMA.Automata.Piet.Types.DirectionPointer
    HelVM.HelMA.Automata.Piet.Types.Hue
    HelVM.HelMA.Automata.Piet.Types.Matrix
    HelVM.HelMA.Automata.Piet.Types.InstructionMemory
    HelVM.HelMA.Automata.Piet.Types.Label
    HelVM.HelMA.Automata.Piet.Types.Labelling
    HelVM.HelMA.Automata.Piet.Types.Lightness
    HelVM.HelMA.Automata.Piet.Types.Memory
    HelVM.HelMA.Automata.Piet.Types.Program

    HelVM.HelMA.Automata.Rev.Evaluator

    HelVM.HelMA.Automata.SubLeq.Automaton
    HelVM.HelMA.Automata.SubLeq.Evaluator
    HelVM.HelMA.Automata.SubLeq.Lexer
    HelVM.HelMA.Automata.SubLeq.Symbol

    HelVM.HelMA.Automata.WhiteSpace.API.TokenType
    HelVM.HelMA.Automata.WhiteSpace.Evaluator
    HelVM.HelMA.Automata.WhiteSpace.Lexer
    HelVM.HelMA.Automata.WhiteSpace.OperandParsers
    HelVM.HelMA.Automata.WhiteSpace.Parser
    HelVM.HelMA.Automata.WhiteSpace.SimpleParams
    HelVM.HelMA.Automata.WhiteSpace.Token

    HelVM.HelMA.Automata.Zot.Automaton
    HelVM.HelMA.Automata.Zot.Parser
    HelVM.HelMA.Automata.Zot.Evaluator
    HelVM.HelMA.Automata.Zot.Expression

  build-depends:
      helio
    , containers           <  0.7
    , data-default
    , extra
    , free
    , IfElse
    , ilist
    , list-t
    , monad-logger
    , monad-loops
    , natural-transformation
    , pretty-simple
    , primitive
    , safe
    , transformers
    , type-operators
    , vector
    , vector-th-unbox
    , yjtools

  ghc-options:

executable helma
  import:              common-options
  hs-source-dirs:      hs/app
  main-is:             Main.hs
  other-modules:
    Options

  build-depends:
      helio
    , helma
    , optparse-applicative >= 0.16 && < 0.19
  ghc-options:
    -threaded
    -rtsopts
    -with-rtsopts=-N

test-suite helma-test
  import:              common-options
  type:                exitcode-stdio-1.0
  hs-source-dirs:      hs/test
  main-is:             Main.hs
  other-modules:
    Spec
    Slow
    SpecHook

    HelVM.Expectations
    HelVM.GoldenExpectations

    HelVM.HelMA.Automaton.API.AutoOptionsExtra
    HelVM.HelMA.Automaton.Eff.FreeEffSpec
    HelVM.HelMA.Automaton.Eff.GADTEffSpec
    HelVM.HelMA.Automaton.OptimizerSpec

    HelVM.HelMA.Automata.FileExtra

    HelVM.HelMA.Automata.BrainFuck.EvaluatorSpec
    HelVM.HelMA.Automata.BrainFuck.EvaluatorSpecData
    HelVM.HelMA.Automata.BrainFuck.FileExtra
    HelVM.HelMA.Automata.BrainFuck.InstructionSpec
    HelVM.HelMA.Automata.BrainFuck.ParserSpec

    HelVM.HelMA.Automata.Cat.EvaluatorSpec

    HelVM.HelMA.Automata.ETA.AddressingSpec
    HelVM.HelMA.Automata.ETA.EvaluatorSpec
    HelVM.HelMA.Automata.ETA.FileExtra
    HelVM.HelMA.Automata.ETA.LexerSpec
    HelVM.HelMA.Automata.ETA.OperandParsersSpec

    HelVM.HelMA.Automata.FALSE.FileExtra
    HelVM.HelMA.Automata.FALSE.ParserSpec

    HelVM.HelMA.Automata.LazyK.EvaluatorSpec
    HelVM.HelMA.Automata.LazyK.FileExtra
    HelVM.HelMA.Automata.LazyK.NumberSpec
    HelVM.HelMA.Automata.LazyK.ParserSpec

    HelVM.HelMA.Automata.Piet.EvaluatorCollisionSpec
    HelVM.HelMA.Automata.Piet.EvaluatorStepStateSpec
    HelVM.HelMA.Automata.Piet.FileExtra

    HelVM.HelMA.Automata.Piet.LLVM.SyntaxTestHelper
    HelVM.HelMA.Automata.Piet.LLVM.TestUtils

    HelVM.HelMA.Automata.Piet.LLVM.ImageReaderSpec
    HelVM.HelMA.Automata.Piet.LLVM.ParserSpec
    HelVM.HelMA.Automata.Piet.LLVM.SyntaxVisualizerSpec
    
    HelVM.HelMA.Automata.Piet.LLVM.Internal.CodelSizeSpec
    HelVM.HelMA.Automata.Piet.LLVM.Internal.FillerSpec
    HelVM.HelMA.Automata.Piet.LLVM.Internal.ToRGB8Spec
    HelVM.HelMA.Automata.Piet.LLVM.Internal.WhiteCodelSliderSpec

    HelVM.HelMA.Automata.Rev.EvaluatorSpec

    HelVM.HelMA.Automata.SubLeq.EvaluatorSpec
    HelVM.HelMA.Automata.SubLeq.EvaluatorSpecData
    HelVM.HelMA.Automata.SubLeq.FileExtra
    HelVM.HelMA.Automata.SubLeq.LexerSpec

    HelVM.HelMA.Automata.WhiteSpace.EvaluatorSpec
    HelVM.HelMA.Automata.WhiteSpace.FileExtra
    HelVM.HelMA.Automata.WhiteSpace.OperandParsersSpec
    HelVM.HelMA.Automata.WhiteSpace.ParserSpec

    HelVM.HelMA.Automata.Zot.EvaluatorSpec
    HelVM.HelMA.Automata.Zot.FileExtra

  build-depends:
      hspec
    , hspec-core
    , hspec-expectations-pretty-diff
    , hspec-golden
    , hspec-slow

    , helio
    , helma

    , containers
    , directory
    , filepath
    , interpolatedstring-perl6
    , stm
    , time
    , type-operators
    , vector
    , yjtools

  build-tool-depends:  hspec-discover:hspec-discover == 2.*
  ghc-options:
    -threaded
    -rtsopts
    -with-rtsopts=-N

--benchmark helma-benchmark
--  import:              common-options
--  type:                exitcode-stdio-1.0
--  hs-source-dirs:      hs/benchmark
--  main-is:             Main.hs
--  other-modules:

--    HelVM.HelMA.Automata.FileExtra

--    HelVM.HelMA.Automata.BrainFuck.EvaluatorBenchMark
--    HelVM.HelMA.Automata.BrainFuck.FileExtra

--    HelVM.HelMA.Automata.ETA.EvaluatorBenchMark
--    HelVM.HelMA.Automata.ETA.FileExtra

--    HelVM.HelMA.Automata.SubLeq.EvaluatorBenchMark
--    HelVM.HelMA.Automata.SubLeq.FileExtra

--    HelVM.HelMA.Automata.WhiteSpace.EvaluatorBenchMark
--    HelVM.HelMA.Automata.WhiteSpace.FileExtra

--  build-depends:
--      gauge

--    , helio
--    , helma

--    , filepath

--  ghc-options:
--    -threaded
--    -rtsopts
--    -with-rtsopts=-N
